# NumPy
# 1. Engine for Data

Welcome to the engine room. Before we start analyzing complex datasets in Pandas, we must understand what powers the whole system.

**NumPy** (Numerical Python) is the `cornerstone` of scientific computing.
* **Speed:** it is written in C, so it is extremely fast - especially when processing `Big Data and machine learning`.
* **Structure:** its `ndarray` (n-dimensional array) is a tuned-up Python list with an emphasis on speed and efficiency.
* **Vectorization:** allows performing mathematical operations on entire blocks of data at once (without slow FOR loops).

A Python `list` is like a pile of miscellaneous cargo in the cargo hold. A NumPy `array` is a precisely organized container where every item has its fixed place and the same type. It is hard to search and work in chaos; in a tidy and organized environment, it is easy.

**Overview & Roadmap:**
* creating and generating data arrays (manual, sequences, random data).
* working with dimensions (`Shape`) and reshaping data streams into grids (`Reshape`).
* calculation `vectorization` – performing mathematical operations on entire arrays at once (without loops).
* `indexing` and `slicing` – surgical selection of specific values and areas.
* data `filtering` and anomaly detection using conditions.

## 1.0 System Initialization (Simulation)

First, we must import the library. The standard alias shortcut in the community is `np`.

In [3]:
import numpy as np

## 1.1 Creating Data Arrays

We rarely enter sensor data manually. We often `generate` it manually or load it `as streams`.

### 1.1.1 Manual vs. Automatic Creation

- when creating an **array**, its `data type` and `size` must be determined
- if the data type is not determined, numpy will try to estimate the data type based on the entered values in the array
- data type is determined using dtype - e.g.:
    * int8 - 8-bit integer (-128 to 127)
    * int16 - 16-bit integer (-32,768 to 32,767)
    * int32 - 32-bit integer (-2,147,483,648 to 2,147,483,647) - **standard**
- arrays can also have other data types (str, float, bool ..)

In [ ]:
# 1. creating arrays

# 1D array - basic one-dimensional array
# standard Python list vs NumPy Array
raw_list = [1, 2, 3, 4, 5]
sensor_stream = np.array(raw_list, dtype=np.int32)

print("Sensor Stream:", sensor_stream)
print("Type:", type(sensor_stream))

# 2D array - two-dimensional array
gamma_detection = np.array([[100, 315, 3], [62, 599, 21]], dtype=np.int32) # nested list = matrix / table
print("Detected gamma energy: ", gamma_detection)

# it is also possible to create multidimensional arrays 3D, 4D ..

# we can use an existing collection to create an array
array_from_list = np.array([7, 8, 9]) # from listu
array_from_tuple = np.array((10, 11, 12)) # from tuple
print("Backup sensor results:", array_from_list)
print("Backup security logs:", array_from_tuple)

In [ ]:
# 2. calibration - arrays with pre-filled values
# suitable for array initialization

# array with zeros
calibration_grid = np.zeros((3, 4), dtype=np.int32) # 2D array: 3 rows 4 columns
print("\nCalibration Grid (Zeros):\n", calibration_grid)

# array with ones
signal_boost = np.ones((2, 3)) # 2D array: 2 rows 3 columns
print("\nSignal Boost (Ones):\n", signal_boost)

# creating an array with a sequence
# FROM-TO with a step: using arange(start, stop, step) - similar to range in Python
time_log = np.arange(0, 60, 5) # 0 to 60 seconds, step 5s
print("\nTime Log:", time_log)

# FROM-TO with a number of points: using linspace(start, stop, number_of_points)
# ideal for graphs - creates "points" with the same "distance" between them in the given range
flight_path = np.linspace(0, 100, 5) 
print("\nFlight Bot Asteroid_Path Segments:", flight_path)


Calibration Grid (Zeros):
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Signal Boost (Ones):
 [[1. 1. 1.]
 [1. 1. 1.]]

Time Log: [ 0  5 10 15 20 25 30 35 40 45 50 55]

Flight Path Segments: [  0.  25.  50.  75. 100.]


### 1.1.2. Data Simulation (Random)

The real universe is full of **noise**. To test algorithms, we often need `random data`.

In [ ]:
# random integer data
radiation_levels = np.random.randint(0, 50, size=10) # returns the specified number of ints from the interval
print("Radiation Levels:", radiation_levels)

# random float data
signal_strength = np.random.rand(5) # returns the specified number of floats
print("Signal Strength:", signal_strength)

Radiation Levels: [11  1 25 16 20 29 12  6 19 48]
Signal Strength: [0.37138821 0.11063919 0.11784921 0.12424031 0.95094133]


## 1.2. Exploration and Shape (Shape & Reshape)

Data often arrives as a long, unstructured **stream / sequence (1D stream)**. To find patterns in them, we often have to `rearrange` them into a table or matrix.

Let's say the probe sends data row by row, but we receive it as one long series of values:

In [ ]:
# raw data stream from a thermal camera (12 pixels)
raw_thermal_data = np.array([22, 24, 25, 28, 30, 32, 31, 29, 25, 23, 21, 20])

# shape - shape of the array (number of dimensions and their size)
print(f"Shape: {raw_thermal_data.shape}") # (12,) - 1D array, 12 elements
print(f"Dimensions: {raw_thermal_data.ndim}") # number of dimensions (0-point, 1-row, 2-table..)
print(f"Data Type: {raw_thermal_data.dtype}") # data type (int32, int64 ..)

# RESHAPE: transformation of data "stream" into a 3x4 grid / table (thermal grid)
# - the order of elements remains the same
# - after reshape, there must be the same number of elements as before
thermal_grid = raw_thermal_data.reshape(3, 4) # 3 rows, 4 columns (= 12 elements)

print("\nThermal Grid (3x4):\n", thermal_grid)
print(f"New Shape: {thermal_grid.shape}") # (3, 4) - 2D array with 3 rows and 4 columns = 12 elements

Shape: (12,)
Dimensions: 1
Data Type: int64

Thermal Grid (3x4):
 [[22 24 25 28]
 [30 32 31 29]
 [25 23 21 20]]
New Shape: (3, 4)


## 1.3. Mathematics and Vectorization (Key Feature!)

This is the reason why using NumPy is worth it. If we want to perform an operation for all numbers in a Python list, we have to write a for loop. In NumPy, we do it **all at once**. It is like giving one order to the entire reconnaissance unit instead of each member individually.

In [ ]:
# Analyzing the thermal grid

print(f"Max Temperature: {np.max(thermal_grid)} C") # max value
print(f"Min Temperature: {np.min(thermal_grid)} C") # min value
print(f"Average Temperature: {np.mean(thermal_grid):.2f} C") # average
print(f"Standard Deviation: {np.std(thermal_grid):.2f}") # standard deviation

Max Temperature: 32 C
Min Temperature: 20 C
Average Temperature: 25.83 C
Standard Deviation: 3.89


### 1.3.1. Vector Operations (Broadcasting)
Let's imagine we need to **calibrate** sensors – add 2 degrees to all values.

In [ ]:
# Python (Slow loop = DON'T DO THIS with large data)
# for i in range(len(data)): data[i] += 2

# NumPy (Vectorization = fast and clean work)
calibrated_grid = thermal_grid + 2

print("Original:\n", thermal_grid)
print("\nCalibrated (+2):\n", calibrated_grid)

# logical and comparison methods with boolean result (True/False)
print("\nIs temperature critical (> 30)?\n", calibrated_grid > 30)

Original:
 [[22 24 25 28]
 [30 32 31 29]
 [25 23 21 20]]

Calibrated (+2):
 [[24 26 27 30]
 [32 34 33 31]
 [27 25 23 22]]

Is temperature critical (> 30)?
 [[False False False False]
 [ True  True  True  True]
 [False False False False]]


## 1.4. Indexing and Slicing (Targeting Data)

We need to surgically target and extract **specific data** from our matrix. NumPy uses the format [row, column] - `index position of the element`.

In [ ]:
sector_map = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])

# 1. specific element [row, column]
print("Element at [0,0]:", sector_map[0, 0])

# 2. slicing - we get the second row
print("Second row (Sector 2):", sector_map[1, :])

# 3. slicing - we get the last column
print("Last column (Sensor C):", sector_map[:, 2])

Element at [0,0]: 10
Second row (Sector 2): [20 21 22]
Last column (Sensor C): [12 22 32]


### 1.4.1. View vs. Copy (Data Safety)

Watch out for memory management.

`View:` **Look** at the data. `Changing the View reflects in the original too`. Efficient and fast memory work - we don't create new data, we just adjust the **view** and **scope** according to what interests us .. the data is still the same

`Copy:` A real clone of the data. `Safe for experiments` = when we want to work with data independently, without affecting the original data

In [ ]:
# creating a VIEW - SLICING in NP (unlike Python lists) creates a VIEW automatically!
sub_sector = sector_map[0:2, 0:2]
print("View BEFORE modification:\n", sub_sector)

# modifying the view
sub_sector[0, 0] = 999

print("Modified View:\n", sub_sector)
print("\nOriginal Map (Affected!):\n", sector_map)
# 999 will appear in the original too

# creating a COPY
delta_sector = sector_map.copy()

Modified View:
 [[10 11]
 [20 21]]
Modified View:
 [[999  11]
 [ 20  21]]

Original Map (Affected!):
 [[999  11  12]
 [ 20  21  22]
 [ 30  31  32]]


## 1.5 Filtration (Searching for Anomalies)

How to quickly find values that exceed limits in a data stream?

In [ ]:
telemetry = np.array([100, 102, 98, 150, 101, 99, 450, 100])

# direct filtering - returns elements that meet the condition
anomalies = telemetry[telemetry > 120]
print("Detected Anomalies:", anomalies)

# using the "where" condition - returns indices of elements meeting the condition
anomaly_indices = np.where(telemetry > 120) # results in the form of a tuple
print("Indices of anomalies:", anomaly_indices)
print(telemetry[3])
print(telemetry[6])

Detected Anomalies: [150 450]
Indices of anomalies: (array([3, 6]),)
150
450


## Practise - Engine Room Training

### practise I: Solar Panel Analysis
We received a raw data stream from the main probe, representing the efficiency of individual cells of the solar array. The data arrived in one long series, but the solar array is actually a grid.

**Assignment:**
1.  Create an array (`solar_stream`) containing **20 random integers** in the range 0 to 100 (representing % efficiency).
2.  Reshape this stream into a matrix (grid) with dimensions **4 rows and 5 columns**.
3.  Calculate and print the **average efficiency** of the entire array.
4.  Find and display the **maximum value** in the grid (the most efficient cell).

---

### practise II: Radiation Anomaly Detection (Vectorization & Filtering)
Sensors on the ship's hull measure radiation levels. Values are in "safe units". We must perform re-calibration and immediately isolate critical values.

**Assignment:**
1.  Create an array (`raw_readings`) containing numbers from **10 to 50** (inclusive) with a step of **5**.
2.  **Vectorization:** Sensor calibration after a solar storm requires multiplying all values by **3.5**. Do this without using a loop. Save results to the variable `calibrated_readings`.
3.  **Filtration:** Print only those calibrated values that are **higher than 100** (critical level).

## Homework (Project: Mars)
We are commencing primary data collection from the surface of Mars.

**Mission:** Our task is to process the first batch of telemetry from the landing module using NumPy.

**Goal:** Create a script in `mars_analaysis_01.ipynb` that will simulate and analyze data about the atmosphere and terrain.

---

### Assignment:

**1. Atmospheric Log (Data Creation):**
* Create a timeline (`time_log`) for the first **24 hours** of measurement (values 0 to 23).
* We will simulate temperature measurement (`temp_readings`) - create an array of 24 random numbers in the range **-100 to -20 °C**.

**2. Topographic Scan (Reshape):**
* The Rover sent a raw data stream from LiDAR (elevation map). **100 numbers** arrived (random values 0 to 500 meters) in one row.
* Save this data to the variable `raw_terrain`.
* Reformat this stream into a **sector map (matrix)** of size **10x10**.

**3. Environment Analysis (Statistics):**
* Calculate and print the **average temperature** for the last 24 hours.
* Find and print the **highest point** in the scanned sector (max value in the terrain map).

**4. Sensor Calibration (Vectorization):**
* We discovered that the temperature sensor has a systematic error and shows **5 degrees more** than reality.
* Perform a correction of the entire `temp_readings` array (subtract 5) - without using a loop.
* Print the first 5 values of the corrected array.

---
#### © Jiří Svoboda (George Freedom)
- Web: https://GeorgeFreedom.com
- LinkedIn: https://www.linkedin.com/in/georgefreedom/
- Let's talk: https://cal.com/georgefreedom